// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/create_event": {
            "post": {
                "description": "Создаёт новое событие",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Создать событие",
                "parameters": [
                    {
                        "description": "JSON события",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.Event"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Созданное событие в поле result",
                        "schema": {
                            "$ref": "#/definitions/web.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Ошибка логики",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/delete_event": {
            "delete": {
                "description": "Удаляет событие по ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Удалить событие",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID события",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Удалённое событие",
                        "schema": {
                            "$ref": "#/definitions/web.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Событие не найдено",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Ошибка логики",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events_for_day": {
            "get": {
                "description": "Возвращает события пользователя за указанный день",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить события за день",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "События за день",
                        "schema": {
                            "$ref": "#/definitions/web.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Ошибка логики",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events_for_month": {
            "get": {
                "description": "Возвращает события пользователя за месяц",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить события за месяц",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "События за месяц",
                        "schema": {
                            "$ref": "#/definitions/web.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Ошибка логики",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events_for_week": {
            "get": {
                "description": "Возвращает события пользователя за неделю",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить события за неделю",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "События за неделю",
                        "schema": {
                            "$ref": "#/definitions/web.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Ошибка логики",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/update_event": {
            "post": {
                "description": "Обновляет событие по указанному ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Обновить событие",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID события",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "JSON события",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Обновлённое событие",
                        "schema": {
                            "$ref": "#/definitions/web.ResultResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Событие не найдено",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Ошибка логики",
                        "schema": {
                            "$ref": "#/definitions/web.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "store.Event": {
            "description": "Событие",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "web.ResultResponse": {
            "type": "object",
            "properties": {
                "result": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Event API",
	Description:      "REST API для работы с событиями: создание, изменение, удаление и получение событий за день, неделю и месяц.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
